#!/usr/bin/env bash

if [[ -z "$1" ]]; then
    echo "Usage: theme_apply.sh <wallpaper_path>"
    exit 1
fi

WALLPAPER="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
THEME_DIR="$HOME/.config/quickshell/themes"

# 1. Extract theme data
JSON=$("$SCRIPT_DIR/colour_extract.py" "$WALLPAPER")
if [[ $? -ne 0 ]] || [[ -z "$JSON" ]]; then
    echo "Failed to extract colours"
    exit 1
fi

ACCENT=$(echo "$JSON" | jq -r '.accent')
SECONDARY=$(echo "$JSON" | jq -r '.secondary_accent')
BACKGROUND=$(echo "$JSON" | jq -r '.background')
FOREGROUND=$(echo "$JSON" | jq -r '.foreground')

ACCENT_NO_HASH=${ACCENT#\#}
SECONDARY_NO_HASH=${SECONDARY#\#}

# Get the active monitor dynamically so this works on both laptop (eDP-1) and desktop (DP-1)
MONITOR=$(hyprctl monitors -j | jq -r '.[0].name')

# 2. Set Wallpaper (live)
hyprctl hyprpaper wallpaper "$MONITOR,$WALLPAPER,cover"

# 2.5 Persist Wallpaper to hyprpaper.conf
cat > ~/.config/hypr/hyprpaper.conf <<EOF
splash = false
wallpaper {
    monitor = $MONITOR
    path = $WALLPAPER
    fit_mode = cover
}
EOF

# 3. Apply Hyprland Borders (persistent)
sed -i -E "s/active_border\s*=\s*\"rgba?\([0-9a-fA-F]+\)\"/active_border = \"rgb(${SECONDARY_NO_HASH})\"/" ~/.config/hypr/hyprland.lua
sed -i -E "s/inactive_border\s*=\s*\"rgba?\([0-9a-fA-F]+\)\"/inactive_border = \"rgb(${ACCENT_NO_HASH})\"/" ~/.config/hypr/hyprland.lua

# 4. Reload Hyprland to apply borders
hyprctl reload

# 5. Apply hyprlock Wallpaper and Colours
FOREGROUND_NO_HASH=${FOREGROUND:1}
sed -i -E "s|path\s*=\s*.*|path = $WALLPAPER|" ~/.config/hypr/hyprlock.conf
sed -i -E "s/^\s*outer_color\s*=\s*.*/    outer_color = rgb(${SECONDARY_NO_HASH})/" ~/.config/hypr/hyprlock.conf
sed -i -E "s/^\s*check_color\s*=\s*.*/    check_color = rgb(${ACCENT_NO_HASH})/" ~/.config/hypr/hyprlock.conf
sed -i -E "s/^\s*font_color\s*=\s*.*/    font_color = rgb(${FOREGROUND_NO_HASH})/" ~/.config/hypr/hyprlock.conf
sed -i -E "s/^\s*color\s*=\s*.*/    color = rgb(${FOREGROUND_NO_HASH})/" ~/.config/hypr/hyprlock.conf

# 6. Apply Kitty Theme
KITTY_THEME="$HOME/.config/kitty/current-theme.conf"
cat > "$KITTY_THEME" <<EOF
# vim:ft=kitty
# Generated by QuickShell Theme Switcher

foreground $FOREGROUND
background $BACKGROUND
selection_foreground $BACKGROUND
selection_background $FOREGROUND

cursor $ACCENT
cursor_text_color $BACKGROUND

url_color $ACCENT

active_border_color $ACCENT
inactive_border_color $SECONDARY
bell_border_color $ACCENT
visual_bell_color none

wayland_titlebar_color $BACKGROUND
macos_titlebar_color $BACKGROUND

active_tab_foreground $BACKGROUND
active_tab_background $ACCENT
inactive_tab_foreground $FOREGROUND
inactive_tab_background $BACKGROUND
tab_bar_background $BACKGROUND
tab_bar_margin_color none

mark1_foreground $BACKGROUND
mark1_background $ACCENT
mark2_foreground $BACKGROUND
mark2_background $SECONDARY
mark3_foreground $BACKGROUND
mark3_background $FOREGROUND

color0 $(echo "$JSON" | jq -r '.palette.color0')
color8 $(echo "$JSON" | jq -r '.palette.color8')
color1 $(echo "$JSON" | jq -r '.palette.color1')
color9 $(echo "$JSON" | jq -r '.palette.color9')
color2 $(echo "$JSON" | jq -r '.palette.color2')
color10 $(echo "$JSON" | jq -r '.palette.color10')
color3 $(echo "$JSON" | jq -r '.palette.color3')
color11 $(echo "$JSON" | jq -r '.palette.color11')
color4 $(echo "$JSON" | jq -r '.palette.color4')
color12 $(echo "$JSON" | jq -r '.palette.color12')
color5 $(echo "$JSON" | jq -r '.palette.color5')
color13 $(echo "$JSON" | jq -r '.palette.color13')
color6 $(echo "$JSON" | jq -r '.palette.color6')
color14 $(echo "$JSON" | jq -r '.palette.color14')
color7 $(echo "$JSON" | jq -r '.palette.color7')
color15 $(echo "$JSON" | jq -r '.palette.color15')
EOF

# Reload Kitty
pkill -USR1 kitty

# 7. Apply Rofi Theme
ROFI_THEME="$HOME/.config/rofi/colors.rasi"
mkdir -p "$HOME/.config/rofi"
cat > "$ROFI_THEME" <<EOF
* {
    bg: ${BACKGROUND}E6;
    accent: ${ACCENT};
    selection-bg: ${SECONDARY};
    white: ${FOREGROUND};
    black: ${BACKGROUND};
}
EOF

# 8. Apply Yazi Theme
YAZI_THEME="$HOME/.config/yazi/theme.toml"
mkdir -p "$HOME/.config/yazi"
cat > "$YAZI_THEME" <<EOF
[manager]
cwd = { fg = "${ACCENT}", bold = true }
hovered = { bg = "${SECONDARY}", fg = "${BACKGROUND}" }
tab_active = { bg = "${ACCENT}", fg = "${BACKGROUND}" }
tab_inactive = { bg = "${BACKGROUND}", fg = "${FOREGROUND}" }
border_style = { fg = "${SECONDARY}" }

[status]
mode_normal = { bg = "${ACCENT}", fg = "${BACKGROUND}", bold = true }
mode_select = { bg = "${SECONDARY}", fg = "${BACKGROUND}", bold = true }
mode_unset  = { bg = "${SECONDARY}", fg = "${BACKGROUND}", bold = true }
progress_normal = { fg = "${ACCENT}", bg = "${BACKGROUND}" }
progress_error  = { fg = "${SECONDARY}", bg = "${BACKGROUND}" }

[input]
border = { fg = "${ACCENT}" }
selected = { bg = "${SECONDARY}", fg = "${BACKGROUND}" }

[select]
border = { fg = "${ACCENT}" }
active = { fg = "${SECONDARY}", bold = true }

[filetype]
rules = [
    { mime = "inode/directory", fg = "${ACCENT}" }
]
EOF

# 9. Apply GTK Theme
GTK_THEME_DIR="$HOME/.config/gtk-3.0"
mkdir -p "$GTK_THEME_DIR"
cat > "$GTK_THEME_DIR/theme_colors.css" <<EOF
@define-color theme_accent ${ACCENT};
@define-color theme_secondary ${SECONDARY};
EOF

# 10. Persist to JSON
mkdir -p "$THEME_DIR"
echo "$JSON" > "$THEME_DIR/active.json"

# 8. Update QuickShell (live)
quickshell ipc call theme apply_colours "$WALLPAPER" "$ACCENT" "$SECONDARY" "$BACKGROUND" "$FOREGROUND"
