general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # screen on after sleep.
}

listener {
    timeout = 60                                 # 3 minutes
    on-timeout = loginctl lock-session            # lock screen
}

listener {
    timeout = 80                                 # 3.5 minutes
    on-timeout = systemctl suspend                # put computer to sleep
    on-resume = hyprctl dispatch dpms on          # screen on
}