general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # screen on after sleep.
}

listener {
    timeout = 60                                 # 1 minute
    on-timeout = playerctl status 2>/dev/null | grep -q "Playing" || loginctl lock-session
}

listener {
    timeout = 80                                 # 1.3 minutes
    on-timeout = playerctl status 2>/dev/null | grep -q "Playing" || systemctl suspend
    on-resume = hyprctl dispatch dpms on          # screen on
}