general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = /home/diego/.local/share/wallpapers/astronaut2.png
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.75
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgb(F5F7F6)
    font_size = 110
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 160
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %B %d")"
    color = rgb(F5F7F6)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Semibold
    position = 0, 80
    halign = center
    valign = center
}

# USER GREETING
label {
    monitor =
    text = cmd[update:60000] echo "hello, $USER"
    color = rgb(F5F7F6)
    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -30
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.35
    dots_center = true
    
    outer_color = rgb(7197CB)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(F5F7F6)
    fade_on_empty = false
    rounding = -1
    
    placeholder_text = <i><span foreground="##dfeefc99">󰌾  Password</span></i>
    hide_input = false
    
    check_color = rgb(9FD0DD)
    fail_color = rgba(235, 77, 75, 0.8)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    
    position = 0, -100
    halign = center
    valign = center
}