[manager]
cwd = { fg = "#DDCB9D", bold = true }
hovered = { bg = "#D2571B", fg = "#413327" }
tab_active = { bg = "#DDCB9D", fg = "#413327" }
tab_inactive = { bg = "#413327", fg = "#DDCB9D" }
border_style = { fg = "#D2571B" }

[status]
mode_normal = { bg = "#DDCB9D", fg = "#413327", bold = true }
mode_select = { bg = "#D2571B", fg = "#413327", bold = true }
mode_unset  = { bg = "#D2571B", fg = "#413327", bold = true }
progress_normal = { fg = "#DDCB9D", bg = "#413327" }
progress_error  = { fg = "#D2571B", bg = "#413327" }

[input]
border = { fg = "#DDCB9D" }
selected = { bg = "#D2571B", fg = "#413327" }

[select]
border = { fg = "#DDCB9D" }
active = { fg = "#D2571B", bold = true }

[filetype]
rules = [
    { mime = "inode/directory", fg = "#DDCB9D" }
]
